export default async function initializeListings(e){var t,r,i,n,a,o,l,d,s;"loaded"!==e.dataset.status&&({createElement:t,markLoaded:r,formatDate:i,truncateText:n,updatePicture:a,createCropConfig:o}=await import("../../../scripts/app.js"),(s=extractSource(e))?(l=(l=1<(l=[...e.children]).length?l[1]:null)?l.cloneNode(!0):null,(d=[...e.classList].filter(e=>/^(?:\d+|(?:sm|md|lg|xl|xxl)-\d+)$/.test(e)).map(e=>"col-"+e)).length||d.push("col-md-6"),e.innerHTML="",0===(s=await fetchListings(s)).length?e.appendChild(buildEmptyState(l,t)):e.appendChild(buildArticleGrid(s,d,{createElement:t,formatDate:i,truncateText:n,updatePicture:a,createCropConfig:o}))):console.error("Listings: no JSON source found"),r(e,"listings"))}function extractSource(e){var e=e.querySelector("a[href]");return(e=e&&e.getAttribute("href"))&&e.split("?")[0].endsWith(".json")?e:null}async function fetchListings(e){try{var t=await fetch(e,{headers:{Accept:"application/json","X-Requested-With":"XMLHttpRequest"}});if(t.ok)return(await t.json()).data||[];throw new Error("HTTP "+t.status)}catch(e){return console.error("Listings fetch error:",e),[]}}function buildArticleGrid(e,i,n){let a=n.createElement;var t=a("div",["container"]);let o=a("div",["row","g-4"]);return e.forEach((e,t)=>{var r=a("div",i);r.appendChild(buildArticleCard(e,t,n)),o.appendChild(r)}),t.appendChild(o),t}function buildArticleCard(e,t,r){var i,{createElement:r,formatDate:n,truncateText:a,updatePicture:o,createCropConfig:l}=r,d=r("a",["article-card"],{href:e.url||"#",title:e.title||""}),s=r("div",["article-card-image"]),c=(e.image_listing?(i=r("picture"),c=r("img",["article-card-img"],{src:e.image_listing,alt:e.title||"",width:"600",height:"338",loading:t<2?"eager":"lazy"}),i.appendChild(c),o(i,[{width:600,media:"(min-width: 768px)"},{width:400}],{context:{isCritical:0===t},crop:l(600,338)}),s.appendChild(i)):s.innerHTML=buildPlaceholderSVG(e.pillar),d.appendChild(s),r("div",["article-card-body"])),o=r("div",["article-card-meta"]),t=(e.category&&((t=r("span",["article-card-category"])).textContent=e.category,o.appendChild(t)),e.publish_date&&((l=r("span",["article-card-date"])).textContent=n(e.publish_date),o.appendChild(l)),c.appendChild(o),e.title&&((i=r("h3")).textContent=e.title,c.appendChild(i)),e.description&&((s=r("p")).textContent=a(e.description,200),c.appendChild(s)),r("span",["learn-more"]));return t.innerHTML='Read More <span class="arrow">&rarr;</span>',c.appendChild(t),d.appendChild(c),d}function buildPlaceholderSVG(e){return`<svg viewBox="0 0 320 180" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g transform="translate(160,82)" opacity="0.18">
      <path d="M-9,-42 L0,-16 L9,-42" stroke="#ffffff" stroke-width="4" stroke-linejoin="round" fill="none" transform="rotate(0)"/>
      <path d="M-9,-42 L0,-16 L9,-42" stroke="#ffffff" stroke-width="4" stroke-linejoin="round" fill="none" transform="rotate(72)"/>
      <path d="M-9,-42 L0,-16 L9,-42" stroke="#ffffff" stroke-width="4" stroke-linejoin="round" fill="none" transform="rotate(144)"/>
      <path d="M-9,-42 L0,-16 L9,-42" stroke="#ffffff" stroke-width="4" stroke-linejoin="round" fill="none" transform="rotate(216)"/>
      <path d="M-9,-42 L0,-16 L9,-42" stroke="#ffffff" stroke-width="4" stroke-linejoin="round" fill="none" transform="rotate(288)"/>
    </g>
    ${e?`<text x="160" y="148" text-anchor="middle" fill="#E8A012"
        font-family="Satoshi, sans-serif" font-size="12" font-weight="700"
        letter-spacing="0.2em" text-rendering="geometricPrecision"
      >${escapeXml(e.toUpperCase())}</text>`:""}
  </svg>`}function escapeXml(e){return e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function buildEmptyState(e,t){var r=t("div",["container"]),i=t("div",["row","justify-content-center"]),n=t("div",["col-lg-6"]),a=t("div",["coming-soon"]);if(e)for(var o=e.querySelector(":scope > div")||e;o.firstChild;)a.appendChild(o.firstChild);else{e=t("h3"),t=(e.textContent="More Insights on the Way",t("p"));t.textContent="We're preparing our first insights on Adobe Experience Cloud architecture, migration strategies, and enterprise activation. Check back soon.",a.appendChild(e),a.appendChild(t)}return n.appendChild(a),i.appendChild(n),r.appendChild(i),r}