let CHEVRON_SVG='<svg class="nav-dropdown-chevron" width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>',ARROW_SVG='<svg class="nav-dropdown-arrow" width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M1 7h11M8 3l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>',LIGHT_NAV_PAGES=["contact"];export default async function initializeNav(e){var t,a;"loaded"!==e.dataset.status&&({createElement:t,markLoaded:a}=await import("../../../scripts/app.js"),buildNavbar(e,{createElement:t}),a(e,"nav"))}function buildNavbar(e,{createElement:t}){var a=LIGHT_NAV_PAGES.some(e=>document.body.classList.contains(e)),a=(e.classList.add("navbar","navbar-expand-lg","fixed-top"),a||e.classList.add("navbar-dark"),e.id="mainNav",[...e.children]),n=a[0],a=a[1],r=t("div",["container"]),n=n?.querySelector("a"),o=(n&&(n.classList.remove("btn","btn-link","btn-primary"),n.classList.add("navbar-brand"),n.id="navbarBrand",o=n.textContent.trim(),n.innerHTML=`<svg class="logo-mark" id="navbarLogo" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
      <g class="navbar-wheel-group" transform="translate(60,60)">
        <g class="navbar-v-group" data-index="0">
          <path d="M-9,-42 L0,-16 L9,-42" stroke="currentColor" stroke-width="4" stroke-linejoin="round" fill="none"/>
        </g>
        <g class="navbar-v-group" data-index="1">
          <path d="M-9,-42 L0,-16 L9,-42" stroke="currentColor" stroke-width="4" stroke-linejoin="round" fill="none"/>
        </g>
        <g class="navbar-v-group" data-index="2">
          <path d="M-9,-42 L0,-16 L9,-42" stroke="currentColor" stroke-width="4" stroke-linejoin="round" fill="none"/>
        </g>
        <g class="navbar-v-group" data-index="3">
          <path d="M-9,-42 L0,-16 L9,-42" stroke="currentColor" stroke-width="4" stroke-linejoin="round" fill="none"/>
        </g>
        <g class="navbar-v-group" data-index="4">
          <path d="M-9,-42 L0,-16 L9,-42" stroke="currentColor" stroke-width="4" stroke-linejoin="round" fill="none"/>
        </g>
      </g>
    </svg>`,(s=t("span",["navbar-brand-text"],{id:"navbarBrandText"})).textContent=o||"5th Revolution",n.appendChild(s),r.appendChild(n)),t("button",["navbar-toggler"],{type:"button","data-bs-toggle":"collapse","data-bs-target":"#navbarNav","aria-controls":"navbarNav","aria-expanded":"false","aria-label":"Toggle navigation"})),s=(o.innerHTML='<span class="navbar-toggler-icon"></span>',r.appendChild(o),a?.querySelector("ul"));if(s){s.classList.add("navbar-nav","align-items-lg-center");for(var i of s.querySelectorAll(":scope > li")){i.classList.add("nav-item");var d,l,p=i.querySelector(":scope > a");p&&(d=p.classList.contains("btn-primary"),l=i.querySelector(":scope > ul"),p.classList.remove("btn","btn-link"),d?(i.classList.add("ms-lg-3"),p.classList.add("btn","btn-primary")):l?transformDropdown(i,p,l,{createElement:t}):(p.classList.add("nav-link"),p.classList.length||p.removeAttribute("class")))}n=t("div",["collapse","navbar-collapse","justify-content-end"],{id:"navbarNav"});n.appendChild(s),r.appendChild(n)}for(;e.firstChild;)e.removeChild(e.firstChild);e.appendChild(r)}function transformDropdown(e,t,a,{createElement:n}){var r,o="dropdown-"+t.textContent.trim().toLowerCase().replace(/\s+/g,"-"),e=(e.classList.add("nav-dropdown"),t.classList.add("nav-link","nav-dropdown-toggle"),t.setAttribute("aria-expanded","false"),t.setAttribute("aria-haspopup","true"),t.setAttribute("aria-controls",o),t.insertAdjacentHTML("beforeend"," "+CHEVRON_SVG),a.classList.add("nav-dropdown-menu"),a.id=o,a.setAttribute("role","menu"),a.setAttribute("aria-label",t.textContent.trim()+" submenu"),a.querySelectorAll(":scope > li"));for(r of e){r.classList.add("nav-dropdown-item"),r.setAttribute("role","none");var s=r.querySelector("a");if(s){var i,d,l,p=s.textContent.trim();let e="";for(i of r.childNodes)i.nodeType===Node.TEXT_NODE&&(d=i.textContent.trim())&&(e=d);for(l of[...r.childNodes])l.nodeType===Node.TEXT_NODE&&l.remove();s.classList.remove("btn","btn-link","btn-primary"),s.classList.add("nav-dropdown-link"),s.setAttribute("role","menuitem"),s.textContent="";var v=n("span",["nav-dropdown-name"]);v.textContent=p,s.appendChild(v),e&&((p=n("span",["nav-dropdown-desc"])).textContent=e,s.appendChild(p))}}o=n("li",["nav-dropdown-footer"],{role:"none"}),e=n("a",["nav-dropdown-link","nav-dropdown-viewall"],{href:t.getAttribute("href")||"/services/",role:"menuitem"});e.innerHTML='<span class="nav-dropdown-name">View All Services</span> '+ARROW_SVG,o.appendChild(e),a.appendChild(o)}